#include <iostream>
#include <vector>
#include <algorithm>

\
void maxHeapify(std::vector<int>& arr, int heapSize, int i) {
    int largest = i;          
    int left = 2 * i + 1;     
    int right = 2 * i + 2;    

    
    if (left < heapSize && arr[left] > arr[largest]) {
        largest = left;
    }

        if (right < heapSize && arr[right] > arr[largest]) {
        largest = right;
    }

    if (largest != i) {
        std::swap(arr[i], arr[largest]);
        maxHeapify(arr, heapSize, largest);
    }
}


void heapSort(std::vector<int>& arr) {
    int n = arr.size();

    
    for (int i = n / 2 - 1; i >= 0; i--) {
        maxHeapify(arr, n, i);
    }

       for (int i = n - 1; i > 0; i--) {
       
        std::swap(arr[0], arr[i]);

        maxHeapify(arr, i, 0);
    }
}

void printArray(const std::vector<int>& arr) {
    for (int num : arr) {
        std::cout << num << " ";
    }
    std::cout << "\n";
}

int main() {
    std::vector<int> data = {12, 11, 13, 5, 6, 7};
    
    std::cout << "Original array: ";
    printArray(data);

    heapSort(data);

    std::cout << "Sorted array (Ascending): ";
    printArray(data);

    return 0;
}
